# https://github.com/atom/ci/blob/25b04066170a9c9c6888d43bb116396e69a73c34/.travis.yml
# Copyright (c) 2015 GitHub Inc.
# Licensed under the MIT license (see LICENSE.md)

### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES="slima"
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

matrix:
  fast_finish: true
  allow_failures:
    - env:
      - ATOM_CHANNEL=beta
        APM_TEST_PACKAGES="slima"
        ATOM_LINT_WITH_BUNDLED_NODE="true"

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

git:
  depth: 10

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
