### Project specific config ###
language: generic

env:
  global:
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"

  jobs:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

os:
  - linux
  - osx

### Generic setup follows ###
script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/d6a5e2624f9e51ee2791f7ee0920d3690910e733/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

notifications:
  email:
    on_success: never
    on_failure: change

git:
  depth: 10

dist: trusty

addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
